- name: Configure GCP Free-Tier VM
  block:
    - name: Ensure a test directory exists in the remote user's home directory
      file:
        path: "~/test"
        state: directory
        mode: "0755"
    - name: Verify a test directory was successfully created
      debug:
        msg: >
          {%- if create_test_directory | default(true) -%}
            The test directory '~/test' was created successfully.
          {%- else -%}
            The test directory '~/test' was not created successfully.
          {%- endif -%}
    - name: Create a test file in the test directory
      copy:
        content: "Hello from Ansible!"
        dest: "~/test/hello.txt"
        mode: "0644"
