- name: Compute SHA-256 hash of a file
  block:
    - name: Run SHA-256 hash on the specified file
      hash:
        path: "{{ ansible_env.HOME }}/test/hello.txt"
      register: hash_result
    - name: Verify hash 
      debug:
        msg: >
          {%- if hash_result.sha256_hash == expected_sha256 -%}
            The file hash matches the expected SHA-256 value.
          {%- else -%}
            WARNING: The file hash does NOT match! Expected {{ expected_sha256 }} but got {{ hash_result.sha256_hash }}.
          {%- endif -%}
    - name: Debug SHA-256 hash output
      debug:
        msg: "SHA-256 Hash: {{ hash_result.sha256_hash }}"
